name: Build-Test-And-Publish-NuGet-Package
on:
  workflow_run:
    workflows:
      - Bump-and-Tag-Semantic-Version
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Specify the .NET version you are using

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Pack the NuGet package
        run: dotnet pack --no-build --configuration Release --output ./artifacts --version ${{ steps.vars.outputs.PACKAGE_VERSION }}

      - name: Publish the NuGet package
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json