name: Bump-and-Tag-Semantic-Version
on:
  push:
    branches:
      - main
jobs:
    bump-and-tag-version:
      name: Bump and Tag Semantic Version
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: jefflinse/pr-semver-bump@v1.6.0
        name: Bump and Tag Version
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}